# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/03ffd841-c8f9-4326-aa2e-d268e500c94d";
    fsType = "btrfs";
    options = [ "compress=zstd:3" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/03ffd841-c8f9-4326-aa2e-d268e500c94d";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd:3"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/03ffd841-c8f9-4326-aa2e-d268e500c94d";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd:3"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/29F9-798E";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
